export const packages = [
  {
    package_id: 1,
    min_amount: 25.0,
    max_amount: 1499.0,
    roi: 1.5,
    duration: 150,
    binary_bonus: 10.0,
    capping_limit: 1000.0,
    principle_return: 50.0,
    level_one_referral: 7,
    package_name: "BEGINNER",
    status: "Active",
  },
  {
    package_id: 2,
    min_amount: 2501.0,
    max_amount: 20000.0,
    roi: 1.8,
    duration: 140,
    binary_bonus: 10.0,
    capping_limit: 3500.0,
    principle_return: 60.0,
    level_one_referral: 8,
    package_name: "GROW",
    status: "Active",
  },
  {
    package_id: 3,
    min_amount: 20001.0,
    max_amount: 50000.0,
    roi: 2.1,
    duration: 130,
    binary_bonus: 10.0,
    capping_limit: 7000.0,
    principle_return: 80.0,
    level_one_referral: 9,
    package_name: "BANKER",
    status: "Active",
  },
];
